# Generated by Django 4.1.7 on 2023-03-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abril',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=12, null=True)),
                ('siglase', models.CharField(blank=True, db_column='siglaSE', max_length=4, null=True)),
                ('cargalancada', models.CharField(blank=True, db_column='cargaLancada', max_length=12, null=True)),
                ('cargabaixada', models.CharField(blank=True, db_column='cargaBaixada', max_length=12, null=True)),
                ('percentual', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'Abril',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Agosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=12, null=True)),
                ('siglase', models.CharField(blank=True, db_column='siglaSE', max_length=4, null=True)),
                ('cargalancada', models.CharField(blank=True, db_column='cargaLancada', max_length=12, null=True)),
                ('cargabaixada', models.CharField(blank=True, db_column='cargaBaixada', max_length=12, null=True)),
                ('percentual', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'Agosto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dezembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=12, null=True)),
                ('siglase', models.CharField(blank=True, db_column='siglaSE', max_length=4, null=True)),
                ('cargalancada', models.CharField(blank=True, db_column='cargaLancada', max_length=12, null=True)),
                ('cargabaixada', models.CharField(blank=True, db_column='cargaBaixada', max_length=12, null=True)),
                ('percentual', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'Dezembro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fevereiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=12, null=True)),
                ('siglase', models.CharField(blank=True, db_column='siglaSE', max_length=4, null=True)),
                ('cargalancada', models.CharField(blank=True, db_column='cargaLancada', max_length=12, null=True)),
                ('cargabaixada', models.CharField(blank=True, db_column='cargaBaixada', max_length=12, null=True)),
                ('percentual', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'Fevereiro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Janeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=12, null=True)),
                ('siglase', models.CharField(blank=True, db_column='siglaSE', max_length=4, null=True)),
                ('cargalancada', models.CharField(blank=True, db_column='cargaLancada', max_length=12, null=True)),
                ('cargabaixada', models.CharField(blank=True, db_column='cargaBaixada', max_length=12, null=True)),
                ('percentual', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'Janeiro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Julho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=12, null=True)),
                ('siglase', models.CharField(blank=True, db_column='siglaSE', max_length=4, null=True)),
                ('cargalancada', models.CharField(blank=True, db_column='cargaLancada', max_length=12, null=True)),
                ('cargabaixada', models.CharField(blank=True, db_column='cargaBaixada', max_length=12, null=True)),
                ('percentual', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'Julho',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Junho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=12, null=True)),
                ('siglase', models.CharField(blank=True, db_column='siglaSE', max_length=4, null=True)),
                ('cargalancada', models.CharField(blank=True, db_column='cargaLancada', max_length=12, null=True)),
                ('cargabaixada', models.CharField(blank=True, db_column='cargaBaixada', max_length=12, null=True)),
                ('percentual', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'Junho',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=12, null=True)),
                ('siglase', models.CharField(blank=True, db_column='siglaSE', max_length=4, null=True)),
                ('cargalancada', models.CharField(blank=True, db_column='cargaLancada', max_length=12, null=True)),
                ('cargabaixada', models.CharField(blank=True, db_column='cargaBaixada', max_length=12, null=True)),
                ('percentual', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'Maio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=12, null=True)),
                ('siglase', models.CharField(blank=True, db_column='siglaSE', max_length=4, null=True)),
                ('cargalancada', models.CharField(blank=True, db_column='cargaLancada', max_length=12, null=True)),
                ('cargabaixada', models.CharField(blank=True, db_column='cargaBaixada', max_length=12, null=True)),
                ('percentual', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'Março',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Novembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=12, null=True)),
                ('siglase', models.CharField(blank=True, db_column='siglaSE', max_length=4, null=True)),
                ('cargalancada', models.CharField(blank=True, db_column='cargaLancada', max_length=12, null=True)),
                ('cargabaixada', models.CharField(blank=True, db_column='cargaBaixada', max_length=12, null=True)),
                ('percentual', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'Novembro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Outubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=12, null=True)),
                ('siglase', models.CharField(blank=True, db_column='siglaSE', max_length=4, null=True)),
                ('cargalancada', models.CharField(blank=True, db_column='cargaLancada', max_length=12, null=True)),
                ('cargabaixada', models.CharField(blank=True, db_column='cargaBaixada', max_length=12, null=True)),
                ('percentual', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'Outubro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Setembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=12, null=True)),
                ('siglase', models.CharField(blank=True, db_column='siglaSE', max_length=4, null=True)),
                ('cargalancada', models.CharField(blank=True, db_column='cargaLancada', max_length=12, null=True)),
                ('cargabaixada', models.CharField(blank=True, db_column='cargaBaixada', max_length=12, null=True)),
                ('percentual', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'Setembro',
                'managed': False,
            },
        ),
    ]
