# Generated by Django 4.1.7 on 2023-03-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abril',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcu', models.CharField(blank=True, max_length=10, null=True)),
                ('sro', models.CharField(blank=True, db_column='SRO', max_length=8, null=True)),
                ('nomeunidade', models.CharField(blank=True, db_column='nomeUnidade', max_length=50, null=True)),
                ('gerencia', models.CharField(blank=True, db_column='Gerencia', max_length=5, null=True)),
                ('lista', models.CharField(blank=True, db_column='Lista', max_length=4, null=True)),
                ('lancado', models.CharField(blank=True, max_length=18, null=True)),
                ('objeto', models.CharField(blank=True, db_column='Objeto', max_length=13, null=True)),
            ],
            options={
                'db_table': 'Abril',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Agosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcu', models.CharField(blank=True, max_length=10, null=True)),
                ('sro', models.CharField(blank=True, db_column='SRO', max_length=8, null=True)),
                ('nomeunidade', models.CharField(blank=True, db_column='nomeUnidade', max_length=50, null=True)),
                ('gerencia', models.CharField(blank=True, db_column='Gerencia', max_length=5, null=True)),
                ('lista', models.CharField(blank=True, db_column='Lista', max_length=4, null=True)),
                ('lancado', models.CharField(blank=True, max_length=18, null=True)),
                ('objeto', models.CharField(blank=True, db_column='Objeto', max_length=13, null=True)),
            ],
            options={
                'db_table': 'Agosto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dezembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcu', models.CharField(blank=True, max_length=10, null=True)),
                ('sro', models.CharField(blank=True, db_column='SRO', max_length=8, null=True)),
                ('nomeunidade', models.CharField(blank=True, db_column='nomeUnidade', max_length=50, null=True)),
                ('gerencia', models.CharField(blank=True, db_column='Gerencia', max_length=5, null=True)),
                ('lista', models.CharField(blank=True, db_column='Lista', max_length=4, null=True)),
                ('lancado', models.CharField(blank=True, max_length=18, null=True)),
                ('objeto', models.CharField(blank=True, db_column='Objeto', max_length=13, null=True)),
            ],
            options={
                'db_table': 'Dezembro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fevereiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcu', models.CharField(blank=True, max_length=20, null=True)),
                ('sro', models.CharField(blank=True, db_column='SRO', max_length=8, null=True)),
                ('nomeunidade', models.CharField(blank=True, db_column='nomeUnidade', max_length=50, null=True)),
                ('gerencia', models.CharField(blank=True, db_column='Gerencia', max_length=20, null=True)),
                ('lancado', models.CharField(blank=True, max_length=30, null=True)),
                ('objeto', models.CharField(blank=True, db_column='Objeto', max_length=13, null=True)),
            ],
            options={
                'db_table': 'Fevereiro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Janeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcu', models.CharField(blank=True, max_length=10, null=True)),
                ('sro', models.CharField(blank=True, db_column='SRO', max_length=8, null=True)),
                ('nomeunidade', models.CharField(blank=True, db_column='nomeUnidade', max_length=50, null=True)),
                ('gerencia', models.CharField(blank=True, db_column='Gerencia', max_length=20, null=True)),
                ('lancado', models.CharField(blank=True, max_length=30, null=True)),
                ('objeto', models.CharField(blank=True, db_column='Objeto', max_length=13, null=True)),
                ('prazo', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'Janeiro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Julho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcu', models.CharField(blank=True, max_length=10, null=True)),
                ('sro', models.CharField(blank=True, db_column='SRO', max_length=8, null=True)),
                ('nomeunidade', models.CharField(blank=True, db_column='nomeUnidade', max_length=50, null=True)),
                ('gerencia', models.CharField(blank=True, db_column='Gerencia', max_length=5, null=True)),
                ('lista', models.CharField(blank=True, db_column='Lista', max_length=4, null=True)),
                ('lancado', models.CharField(blank=True, max_length=18, null=True)),
                ('objeto', models.CharField(blank=True, db_column='Objeto', max_length=13, null=True)),
            ],
            options={
                'db_table': 'Julho',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Junho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcu', models.CharField(blank=True, max_length=10, null=True)),
                ('sro', models.CharField(blank=True, db_column='SRO', max_length=8, null=True)),
                ('nomeunidade', models.CharField(blank=True, db_column='nomeUnidade', max_length=50, null=True)),
                ('gerencia', models.CharField(blank=True, db_column='Gerencia', max_length=5, null=True)),
                ('lista', models.CharField(blank=True, db_column='Lista', max_length=4, null=True)),
                ('lancado', models.CharField(blank=True, max_length=18, null=True)),
                ('objeto', models.CharField(blank=True, db_column='Objeto', max_length=13, null=True)),
            ],
            options={
                'db_table': 'Junho',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcu', models.CharField(blank=True, max_length=10, null=True)),
                ('sro', models.CharField(blank=True, db_column='SRO', max_length=8, null=True)),
                ('nomeunidade', models.CharField(blank=True, db_column='nomeUnidade', max_length=50, null=True)),
                ('gerencia', models.CharField(blank=True, db_column='Gerencia', max_length=5, null=True)),
                ('lista', models.CharField(blank=True, db_column='Lista', max_length=4, null=True)),
                ('lancado', models.CharField(blank=True, max_length=18, null=True)),
                ('objeto', models.CharField(blank=True, db_column='Objeto', max_length=13, null=True)),
            ],
            options={
                'db_table': 'Maio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcu', models.CharField(max_length=10)),
                ('sro', models.CharField(blank=True, db_column='SRO', max_length=8, null=True)),
                ('nomeunidade', models.CharField(blank=True, db_column='nomeUnidade', max_length=50, null=True)),
                ('gerencia', models.CharField(blank=True, db_column='Gerencia', max_length=8, null=True)),
                ('lista', models.CharField(blank=True, db_column='Lista', max_length=4, null=True)),
                ('lancado', models.CharField(blank=True, max_length=20, null=True)),
                ('objeto', models.CharField(blank=True, db_column='Objeto', max_length=13, null=True)),
            ],
            options={
                'db_table': 'Março',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Novembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcu', models.CharField(blank=True, max_length=10, null=True)),
                ('sro', models.CharField(blank=True, db_column='SRO', max_length=8, null=True)),
                ('nomeunidade', models.CharField(blank=True, db_column='nomeUnidade', max_length=50, null=True)),
                ('gerencia', models.CharField(blank=True, db_column='Gerencia', max_length=5, null=True)),
                ('lista', models.CharField(blank=True, db_column='Lista', max_length=4, null=True)),
                ('lancado', models.CharField(blank=True, max_length=18, null=True)),
                ('objeto', models.CharField(blank=True, db_column='Objeto', max_length=13, null=True)),
            ],
            options={
                'db_table': 'Novembro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Outubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcu', models.CharField(max_length=10)),
                ('sro', models.CharField(blank=True, db_column='SRO', max_length=8, null=True)),
                ('nomeunidade', models.CharField(blank=True, db_column='nomeUnidade', max_length=50, null=True)),
                ('gerencia', models.CharField(blank=True, db_column='Gerencia', max_length=5, null=True)),
                ('lista', models.CharField(blank=True, db_column='Lista', max_length=4, null=True)),
                ('lancado', models.CharField(blank=True, max_length=18, null=True)),
                ('objeto', models.CharField(blank=True, db_column='Objeto', max_length=13, null=True)),
            ],
            options={
                'db_table': 'Outubro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Setembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcu', models.CharField(max_length=10)),
                ('sro', models.CharField(blank=True, db_column='SRO', max_length=8, null=True)),
                ('nomeunidade', models.CharField(blank=True, db_column='nomeUnidade', max_length=50, null=True)),
                ('gerencia', models.CharField(blank=True, db_column='Gerencia', max_length=5, null=True)),
                ('lista', models.CharField(blank=True, db_column='Lista', max_length=4, null=True)),
                ('lancado', models.CharField(blank=True, max_length=18, null=True)),
                ('objeto', models.CharField(blank=True, db_column='Objeto', max_length=13, null=True)),
            ],
            options={
                'db_table': 'Setembro',
                'managed': False,
            },
        ),
    ]
